=== metalizzsas/NusterKit/libs/typings/src/schemas/schema-translations.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "description": "Schema used by translation file",
            "type": "string"
        },
        "addons": {
            "additionalProperties": {
                "type": "string"
            },
            "description": "Addons",
            "type": "object"
        },
        "containers": {
            "additionalProperties": {
                "additionalProperties": false,
                "properties": {
                    "actions": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "description": "Containers actions",
                        "type": "object"
                    },
                    "name": {
                        "description": "Container name",
                        "type": "string"
                    },
                    "regulations": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "description": "String keyed Translations group",
                        "type": "object"
                    }
                },
                "required": [
                    "name"
                ],
                "type": "object"
            },
            "description": "Containers translations",
            "type": "object"
        },
        "cycle": {
            "additionalProperties": false,
            "description": "Cycle translations",
            "properties": {
                "end_reasons": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Cycle end reasons",
                    "type": "object"
                },
                "names": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Cycle names",
                    "type": "object"
                },
                "run_conditions": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Cycle start conditions",
                    "type": "object"
                },
                "steps": {
                    "additionalProperties": {
                        "additionalProperties": false,
                        "properties": {
                            "desc": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "desc",
                            "name"
                        ],
                        "type": "object"
                    },
                    "description": "Cycle steps",
                    "type": "object"
                }
            },
            "required": [
                "end_reasons",
                "names",
                "run_conditions",
                "steps"
            ],
            "type": "object"
        },
        "gates": {
            "additionalProperties": false,
            "description": "IO Gates translations",
            "properties": {
                "categories": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "IO Gates categories",
                    "type": "object"
                },
                "names": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "IO Gates names (Includes full gate name with category such as `levels#act-min-n`)",
                    "type": "object"
                }
            },
            "required": [
                "categories",
                "names"
            ],
            "type": "object"
        },
        "maintenance": {
            "additionalProperties": false,
            "description": "Maintenances translations",
            "properties": {
                "tasks": {
                    "additionalProperties": {
                        "additionalProperties": false,
                        "properties": {
                            "desc": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "desc",
                            "name"
                        ],
                        "type": "object"
                    },
                    "description": "Task specific translation",
                    "type": "object"
                }
            },
            "required": [
                "tasks"
            ],
            "type": "object"
        },
        "profile": {
            "additionalProperties": false,
            "description": "Profiles translations",
            "properties": {
                "categories": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Profile categories translations",
                    "type": "object"
                },
                "premade": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Premade profiles translations",
                    "type": "object"
                },
                "rows": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Profile Rows translations",
                    "type": "object"
                }
            },
            "required": [
                "categories",
                "premade",
                "rows"
            ],
            "type": "object"
        },
        "toasts": {
            "additionalProperties": {
                "additionalProperties": false,
                "description": "Toast translation",
                "properties": {
                    "actions": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "type": "object"
                    },
                    "message": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    }
                },
                "required": [
                    "message",
                    "title"
                ],
                "type": "object"
            },
            "description": "Toasts",
            "type": "object"
        }
    },
    "required": [
        "$schema",
        "addons",
        "containers",
        "cycle",
        "gates",
        "maintenance",
        "profile",
        "toasts"
    ],
    "type": "object"
}

=== metalizzsas/NusterKit/libs/misc/i18n/machines/smoothit-m-2/fr.json
{
    "$schema": "../../../../../../node_modules/@metalizzsas/nuster-typings/build/schemas/schema-translations.json",

    "containers": {

        "eff": {
            "name": "Effluents"
        },

        "resin": {
            "name": "Vernis"
        }
    },
    "profile": {
        "categories": {
            "vapors-extraction": "Extraction des vapeurs",
            "pulverization": "Pulvérisation",
            "uv-curing": "Cuisson UV",
            "inerting": "Inertage",
            "multilayer": "Multicouche",
            "motor": "Moteur de rotation"
        },
        "premade": {
            "sla": "Pièce 3D SLA / DLP"
        },
        "rows": {
            "interlayer-uvduration": "Durée cuisson UV entre les couche",
            "uv-power": "Puissance UV",
            "reverseEnabled": "Invertion moteur",
            "reverseTime": "Delai inversion sens moteur"
        }
    },
    "cycle": {
        "names": {
            "default": "Cycle de base smoothit"
        },
        "end_reasons": {
            "uv-cache-wrong": "Erreur position cache UV",
            "nozzle-cache-wrong": "Erreur position cache buse",
            "security-emergency-stop": "Boutton d'arret d'urgence déclenché",
            "security-nitrogen-sensor": "Pression d'azote trop basse",
            "security-cover-closed": "Couvercle ouvert",
            "security-resin#slot-sensor": "Pot de vernis manquant",
            "security-uv#overheat": "Surchauffe lampe UV"
        },
        "run_conditions": {
            "emergency-stop": "Statut bouton d'arret d'urgence",
            "nitrogen-sensor": "Pression d'azote",
            "cover-closed": "Couvercle fermé",
            "resin#slot-sensor": "Présence du pot de vernis",
            "uv#overheat": "Température de la lampe UV"
        },
        "steps": {
            "start": {
                "name": "Démarrage",
                "desc": "Préchauffe de la machine"
            },
            "pulverization": {
                "name": "Pulvérisation",
                "desc": "Application du vernis sur vos pièces."
            },
            "inerting": {
                "name": "Inertage",
                "desc": "Remplissage de la cuve d'azote pour améliorer la cuisson UV."
            },
            "uv-curing-interlayer": {
                "name": "Cuisson UV",
                "desc": "Durcissement du vernis UV."
            },
            "uv-curing": {
                "name": "Cuisson UV",
                "desc": "Durcissement du vernis UV."
            },
            "vapors-extraction": {
                "name": "Filtrations des vapeurs",
                "desc": "Filtrations des gazs et fines particules produites par le programme."
            }
        }
    },
    "gates": {
        "categories": {
            "motor": "Moteur de rotation",
            "uv": "Ultraviolet",
            "nozzle": "Buse",
            "resin": "Vernis"
        },
        "names": {
            "emergency-stop": "Bouton d'arret d'urgence",
            "nitrogen-sensor": "Pression d'azote",
            "cover-closed": "Couvercle fermé",
            
            "ventilation": "Extraction des vapeurs",
            "air-heater": "Rechauffeur d'air",
            "inerting": "Inertage",
            
            "resin#slot-sensor": "Resin container sensor",
            "resin#pressure": "Resin container pressure",
            
            "uv#sensor-open": "Cache UV Ouvert",
            "uv#sensor-closed": "Cache UV Fermé",
            "uv#overheat": "Surchauffe lampe UV",
            "uv#enable": "Lampe UV",
            "uv#ventil": "Ventilation lampe UV",
            "uv#power": "Puissance lampe UV",
            "uv#cache": "Cache lampe UV",
            
            "motor#direction": "Sens moteur",
            "motor#speed": "Vitesse moteur",
            
            "nozzle#sensor-open": "Cache buse ouver",
            "nozzle#sensor-closed": "Cache buse fermé",
            "nozzle#pulverization": "Pulvérization",
            "nozzle#cache": "Cache buse"
        }
    },

    "maintenance": {
        "tasks": {
            "smt-filter": {
                "name": "Filtre solvants",
                "desc": "Filtre de Smoothit permet de filtrer les solvants, particules et gazs produits par le programme."
            },
            "inner-cleaning": {
                "name": "Masques interne",
                "desc": "Les masque interne evite l'accumulation de vernis dans la cuve."
            },
            "uv-lamp": {
                "name": "Lampe UV",
                "desc": "La lampe UV permet de durcir le vernis de lissage présent sur vos pièces."
            }
        }
    },

    "toasts": {},
    "addons": {}
}

=== metalizzsas/NusterKit/libs/misc/i18n/machines/smoothit-m-3/en.json
{
    "$schema": "../../../node_modules/@metalizzsas/nuster-typings/build/schemas/schema-translations.json",

    "containers": {

        "eff": {
            "name": "Effluents"
        },

        "resin": {
            "name": "Varnish"
        }
    },

    "profile": {
        "categories": {
            "vapors-extraction": "Vapors extraction",
            "pulverization": "Pulverization",
            "uv-curing": "UV curing",
            "inerting": "Inerting",
            "multilayer": "Multilayer",
            "motor": "Rotation Motor"
        },
        "premade": {
            "shiny-polyjet": "Shiny Polyjet",
            "shiny-resin": "Shiny SLA / DLP",

            "translucent-polyjet": "Translucent Polyjet",
            "translucent-resin": "Translucent SLA / DLP"
        },
        "rows": {
            "interlayer-uvduration": "UV Curing time between layers",
            "uv-power": "UV Power",
            "reverseEnabled": "Motor direction reverse",
            "reverseTime": "Motor reverser timer",
            "high-enabled": "High nozzle enabled",
            "low-enabled": "Low nozzle enabled"
        }
    },
    "cycle": {
        "names": {
            "default": "Base smoothit cycle"
        },
        "end_reasons": {
            "uv-cache-wrong": "UV Cache error",
            "nozzle-low-cache-wrong": "Nozzle Low Cache error",
            "nozzle-high-cache-wrong": "Nozzle High Cache error",
            "security-emergency-stop": "Emergency stop button pressed",
            "security-nitrogen-sensor": "Nitrogen pressure too low",
            "security-cover-closed": "Cover open",
            "security-resin#slot-sensor": "Vanish slot missing",
            "security-uv#overheat": "UV lamp overheat"
        },
        "run_conditions": {
            "emergency-stop": "Emergency stop button pressed",
            "nitrogen-sensor": "Nitrogen pressure too low",
            "cover-closed": "Cover open",
            "resin#slot-sensor": "Vanish slot missing",
            "uv#overheat": "UV lamp overheat"
        },
        "steps": {
            "start": {
                "name": "Start",
                "desc": "Preheating machine"
            },
            "pulverization": {
                "name": "Pulverization",
                "desc": "Applying varnish on your parts."
            },
            "inerting": {
                "name": "Inerting",
                "desc": "Filling the machine with nitrogen to ehance UV Curing."
            },
            "uv-curing-interlayer": {
                "name": "UV Curing",
                "desc": "Hardening the varnish on your parts."
            },
            "uv-curing": {
                "name": "UV Curing",
                "desc": "Hardening the varnish on your parts."
            },
            "vapors-extraction": {
                "name": "Vapors filtering",
                "desc": "Filtering gases and thin particules produced by the machine"
            }
        }
    },
    "gates": {
        "categories": {
            "motor": "Rotation Motor",
            "uv": "Ultraviolet",
            "nozzle-high": "Nozzle high",
            "nozzle-low": "Nozzle low",
            "resin": "Varnish"
        },
        "names": {
            "emergency-stop": "Emergency stop button",
            "air-sensor": "Air pressure sensor",
            "nitrogen-sensor": "Nitrogen pressure sensor",
            "cover-closed": "Cover closed",
            "eff-container-sensor": "Effluents container sensor",
            
            "ventilation": "Vapors extraction",
            "ventilation-valve": "3 Way ventilation valve",
            "air-heater": "Air heater",
            "inerting": "Inerting",

            "levels#eff-n": "Effluents limit",
            "resin#slot-sensor": "Varnish container sensor",
            "resin#pressure": "Varnish container pressure",
            
            "uv#sensor-open": "UV cache open",
            "uv#sensor-closed": "UV cache closed",
            "uv#overheat": "UV overheat security",
            "uv#enable": "UV lamp",
            "uv#ventil": "UV lamp ventilation",
            "uv#power": "UV lamp power",
            "uv#cache": "UV lamp cache",
            
            "motor#direction": "Motor direction",
            "motor#speed": "Motor speed",
            
            "nozzle-high#sensor-open": "Nozzle high cache open",
            "nozzle-high#sensor-closed": "Nozzle high cache closed",
            "nozzle-high#pulverization": "Nozzle high pulverization",
            "nozzle-high#cache": "Nozzle high cache",

            "nozzle-low#sensor-open": "Nozzle low cache open",
            "nozzle-low#sensor-closed": "Nozzle low cache closed",
            "nozzle-low#pulverization": "Nozzle low pulverization",
            "nozzle-low#cache": "Nozzle low cache"
        }
    },

    "maintenance": {
        "tasks": {
            "smt-filter": {
                "name": "Filter",
                "desc": "Smoothit filter filters all coating solvants produced by the coating done inside the machine."
            },
            "inner-cleaning": {
                "name": "Inner",
                "desc": "The inner layer masks the machine to avoid vanish accumulation on the cuve."
            },
            "uv-lamp": {
                "name": "UV Lamp",
                "desc": "UV Lamp is used to harden varnish on top of your part."
            }
        }
    },

    "toasts": {},
    "addons": {}
}

=== metalizzsas/NusterKit/libs/misc/i18n/machines/smoothit-m-3/fr.json
{
    "$schema": "../../../node_modules/@metalizzsas/nuster-typings/build/schemas/schema-translations.json",

    "containers": {

        "resin": {
            "name": "Vernis",
            "actions": {
                "load": "Charger le vernis",
                "unload": "Retirer le vernins"
            }
        },

        "eff": {
            "name": "Effluents"
        },

        "eff-water": {
            "name": "Effluents rideau d'eau"
        }
    },

    "profile": {
        "categories": {
            "vapors-extraction": "Extraction des vapeurs",
            "pulverization": "Pulvérisation",
            "uv-curing": "Cuisson UV",
            "inerting": "Inertage",
            "multilayer": "Multicouche",
            "motor": "Moteur de rotation"
        },
        "premade": {
            "shiny": "Brillant",
            "translucent": "Transparent"
        },
        "rows": {
            "sprayOn": "Temps de spray (on)",
            "sprayOff": "Temps de repos spray (off)",
            "sprayCount": "Nombre de sprays",
            "interlayer-uvduration": "Durée cuisson uv entre les couches",
            "uv-power": "Puissance UV",
            "reverseEnabled": "Invertion moteur",
            "reverseTime": "Motor reverser timer",
            "high-enabled": "Buse haut activée",
            "low-enabled": "Buse bas activée",
            "aerosol-cleanup-time": "Temps d'évacuation des aerosols"
        }
    },

    "cycle": {
        "names": {
            "default": "Cycle de base smoothit"
        },
        "end_reasons": {
            "uv-cache-wrong": "Erreur position cache UV",
            "nozzle-low-cache-wrong": "Erreur position cache buse bas",
            "nozzle-high-cache-wrong": "Erreur position cache buse haut",
            "security-emergency-stop": "Boutton d'arret d'urgence déclenché",
            "security-nitrogen-sensor": "Pression d'azote trop basse",
            "security-cover-closed": "Couvercle ouvert",
            "security-resin#slot-sensor": "Pot de vernis manquant",
            "security-uv#overheat": "Surchauffe lampe UV"
        },
        "run_conditions": {
            "emergency-stop": "Statut bouton d'arret d'urgence",
            "nitrogen-sensor": "Pression d'azote",
            "cover-closed": "Couvercle fermé",
            "resin#slot-sensor": "Présence du pot de vernis",
            "uv#overheat": "Température de la lampe UV"
        },
        "steps": {
            "start": {
                "name": "Démarrage",
                "desc": "Préchauffe de la machine"
            },
            "pulverization": {
                "name": "Pulvérisation",
                "desc": "Application du vernis sur vos pièces."
            },
            "inerting": {
                "name": "Inertage",
                "desc": "Remplissage de la cuve d'azote pour améliorer la cuisson UV."
            },
            "uv-curing-interlayer": {
                "name": "Cuisson UV",
                "desc": "Durcissement du vernis UV."
            },
            "uv-curing": {
                "name": "Cuisson UV",
                "desc": "Durcissement du vernis UV."
            },
            "vapors-extraction": {
                "name": "Filtrations des vapeurs",
                "desc": "Filtrations des gazs et fines particules produites par le programme."
            }
        }
    },

    "gates": {
        "categories": {
            "motor": "Moteur de rotation",
            "uv": "Ultraviolet",
            "nozzle-high": "Buse haut",
            "nozzle-low": "Buse bas",
            "resin": "Vernis"
        },
        "names": {
            "emergency-stop": "Bouton d'arret d'urgence",
            "nitrogen-sensor": "Pression d'azote",
            "cover-closed": "Couvercle fermé",
            
            "ventilation": "Extraction des vapeurs",
            "ventilation-valve": "Vanne 3 voies ventilation",
            "water-slide-pump": "Pompe rideau d'eau",
            "inerting": "Inertage",

            "resin#slot-sensor": "Présence du pot de vernis",
            "resin#pressure": "Pression pot de vernis",
            
            "uv#sensor-open": "Cache UV over",
            "uv#sensor-closed": "Cache UV fermé",
            "uv#overheat": "Défaut température lampe UV",
            "uv#enable": "Lampe UV",
            "uv#power": "Puissance lampe UV",
            "uv#cache": "Cache lampe UV",
            
            "motor#direction": "Sens moteur",
            "motor#speed": "Vitesse moteur",
            
            "nozzle-high#sensor-open": "Cache ouvert buse haut",
            "nozzle-high#sensor-closed": "Cache fermé buse haut",
            "nozzle-high#pulverization": "Pulvérisation buse haut",
            "nozzle-high#cache": "Cache buse haut",

            "nozzle-low#sensor-open": "Cache ouvert buse bas",
            "nozzle-low#sensor-closed": "Cache fermé buse bas",
            "nozzle-low#pulverization": "Pulvérisation buse bas",
            "nozzle-low#cache": "Cache buse bas"
        }
    },

    "maintenance": {
        "tasks": {
            "inner-cleaning": {
                "name": "Masque interne",
                "desc": "Le masque interne evite l'accumulation de vernis dans la cuve."
            },
            "eff-container-varnish": {
                "name": "Conteneur de vernis",
                "desc": "Ce conteneur récupère les résidus de vernis après la pulvérisation."
            },
            "eff-container-water": {
                "name": "Conteneur d'eau & vernis",
                "desc": "Ce conteneur récupère les résidus de vernis restant a l'aide d'un rideau d'eau."
            },
            "smt-filter": {
                "name": "Filtre solvants",
                "desc": "Filtre de Smoothit permet de filtrer les solvants, particules et gazs produits par le programme."
            },
            "uv-lamp": {
                "name": "Lampe UV",
                "desc": "La lampe UV permet de durcir le vernis."
            }
        }
    },
    "toasts": {},
    "addons": {}
}

=== metalizzsas/NusterKit/libs/misc/i18n/machines/uscleaner-m-1/it.json
{
    "$schema": "../../../node_modules/@metalizzsas/nuster-typings/build/schemas/schema-translations.json",

    "containers": {
        "bac": {
            "name": "Vasca",

            "regulations": {
                "temperature": "Temperatura"
            },
            "actions": {
                "load": "",
                "unload": ""
            }
        }
    },
    "profile": {

        "premade": {
            "15min": "15 minuti"
        },

        "categories": {
            "principal": "Funzioni principali"
        },
        "rows": {
            "duration": "Durata",
            "target-temperature": "Temperatura",
            "motor-speed": "Velocità del motore"
        }
    },

    "cycle": {
        "end_reasons": {
            "security-emergency-stop": "Pulsante arresto di emergenza inserito",
            "security-cover-closed": "Coperchio aperto",
            "security-temperature#over-heat": "Product overheat"
        },
        "run_conditions": {
            "emergency-stop": "Pulsante arresto di emergenza",
            "cover-closed": "Coperchio chiuso",
            "temperature#over-heat": "No product overheat",
            "usc-filter": "Filtro pulito"
        },

        "names": {
            "default": "Ciclo di base Uscleaner"
        },
        "steps": {
            "cleaning": {
                "name": "Pulizia",
                "desc": "Pulizia dei pezzi"
            }
        }
    },

    "gates": {
        "categories": {
            "motor": "Motore di rotazione",
            "temperature": "Gestione temperatura",
            "levels": "Livelli",
            "pump": "Gestione pompa"
        },
        "names": {
            "emergency-stop": "Pulsante arresto di emergenza",
            "cover-closed": "Sensore coperchio",

            "motor#direction": "Senso di rotazione del motore",
            "motor#speed": "Velocità del motore",

            "temperature#sensor": "Sensore di temperatura",
            "temperature#over-heat": "Fluid overheat",
            "temperature#heater": "Scaldamento della vasca",
            "temperature#ventilation": "Ventilazione dello scambiatore vasca",

            "us-power": "Trasduttori US",

            "pump#pressure": "Pressione in uscita della pompa",
            "pump#enable": "Attivazione della pompa"

        }
    },

    "maintenance": {
        "tasks": {
            "usc-filter": {
                "name": "Filtro",
                "desc": "Il filtro dell'Uscleaner permette di catturare le particelle nella vasca."
            }
        }
    },
    "toasts": {},
    "addons": {
        "temperature-control": "Controllo della temperatura"
    }
}
